---
name: JupyterLab
version: dev
slug: jupyterlablite
description: Create documents containing live code, equations, visualizations, and explanatory text
url: https://github.com/hassio-addons/addon-jupyterlab
codenotary: codenotary@frenck.dev
ingress: true
panel_icon: mdi:flask-outline
arch:
  - aarch64
  - amd64
homeassistant_api: true
init: false
map:
  - config:rw
  - share:rw
options:
  github_access_token: ''
  system_packages: []
  init_commands:
    - pip install hass_pyscript_kernel
    - jupyter pyscript install
    - echo "[homeassistant]" > /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
    # change this to your HA host's IP, see below
    - echo "hass_host = coniferha.ha.home" >> /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
    - echo "hass_url = http://supervisor/core/" >> /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
    - echo "hass_token = $SUPERVISOR_TOKEN" >> /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  github_access_token: password
  system_packages:
    - str
  init_commands:
    - str
